version: "3"
services:
  app:
    image: python:3.11
    build: .
    ports:
      - 9876:9876
    container_name: app
    volumes:
      - ./apps:/apps
      - socket:/tmp
    command: gunicorn -w 4 -b 0.0.0.0:9876 "apps.app:create_app()" 
    restart: always
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
volumes:
  socket: