version: "3.8"
services:
  app:
    container_name: app
    image: python:3.11
    build: .
    ports:
      - 9876:9876
    volumes:
      - ./apps:/apps
      - socket:/tmp
    command: gunicorn -w 4 -b 0.0.0.0:9876 "apps.app:create_app()"
    restart: always
    tty: true

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8081:8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - socket:/tmp
    depends_on:
      - app
    restart: always


volumes:
  socket: