"""empty message

Revision ID: d59cce9fe5d4
Revises: 097e646b35a1
Create Date: 2023-09-12 23:56:57.062519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59cce9fe5d4'
down_revision = '097e646b35a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diary_text', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_column('diary_text')

    # ### end Alembic commands ###
